// Retro Amber Phosphor Monaco Editor Theme (Issue #79)

export const retroTheme = {
  base: 'vs-dark' as const,
  inherit: true,
  rules: [
    { token: 'comment', foreground: 'cc6600', fontStyle: 'italic' },
    { token: 'string', foreground: 'ffb000' },
    { token: 'string.escape', foreground: 'ff9000' },
    { token: 'number', foreground: 'ff9000' },
    { token: 'builtin', foreground: 'ffb000' },
    { token: 'keyword', foreground: 'ff9000', fontStyle: 'bold' },
    { token: 'keyword.control', foreground: 'ff9000', fontStyle: 'bold' },
    { token: 'keyword.operator', foreground: 'ffb000' },
    { token: 'operator', foreground: 'ffb000' },
    { token: 'type', foreground: 'ffb000', fontStyle: 'bold' },
    { token: 'type.primitive', foreground: 'ffb000', fontStyle: 'bold' },
    { token: 'variable', foreground: 'ffb000' },
    { token: 'variable.parameter', foreground: 'ffb000' },
    { token: 'function', foreground: 'ffb000', fontStyle: 'bold' },
    { token: 'constant', foreground: 'ff9000', fontStyle: 'bold' },
    { token: 'invalid', foreground: 'ff0000', background: '0a0800' },
    { token: 'invalid.deprecated', foreground: 'ff6b6b', fontStyle: 'strikethrough' },
  ],
  colors: {
    'editor.background': '#0a0800',
    'editor.foreground': '#ffb000',
    'editor.lineNumbersActiveForeground': '#ffb000',
    'editor.lineNumbersForeground': '#cc6600',
    'editor.selectionBackground': '#662200',
    'editor.selectionHighlightBackground': 'rgba(255, 176, 0, 0.15)',
    'editor.wordHighlightBackground': 'rgba(255, 144, 0, 0.1)',
    'editor.wordHighlightStrongBackground': 'rgba(255, 176, 0, 0.2)',
    'editorCursor.foreground': '#ffb000',
    'editorCursor.background': '#0a0800',
    'editorWhitespace.foreground': 'rgba(255, 176, 0, 0.2)',
    'editorLineNumber.background': '#0a0800',
    'editorLineNumber.foreground': '#cc6600',
    'editorGutter.background': '#0a0800',
    'editorGutter.foreground': '#cc6600',
    'editorGutter.modifiedBackground': '#ff9000',
    'editorGutter.addedBackground': '#50fa7b',
    'editorGutter.deletedBackground': '#ff5555',
    'editorRangeHighlight.background': 'rgba(255, 176, 0, 0.05)',
    'editorError.foreground': '#ff5555',
    'editorWarning.foreground': '#ffb000',
    'editorInfo.foreground': '#8be9fd',
    'editor.findMatchBackground': 'rgba(255, 176, 0, 0.3)',
    'editor.findMatchBorder': '#ffb000',
    'editor.findMatchHighlightBackground': 'rgba(255, 176, 0, 0.15)',
    'editor.findRangeHighlightBackground': 'rgba(255, 176, 0, 0.08)',
    'editorBracketMatch.background': 'rgba(255, 176, 0, 0.2)',
    'editorBracketMatch.border': '#ffb000',
    'editorOverviewRuler.border': '#cc6600',
    'editorOverviewRuler.errorForeground': '#ff5555',
    'editorOverviewRuler.warningForeground': '#ffb000',
    'editorOverviewRuler.infoForeground': '#8be9fd',
    'editorOverviewRuler.bracketMatchForeground': '#ffb000',
  },
};
